from pydantic import BaseModel, Field
from enum import Enum
import re
import time

class Priority(str, Enum):
    Low = 'Low'
    Medium = 'Medium'
    High = 'High'

class Department(str, Enum):
    Billing = 'Billing'
    Tech = 'Tech'
    General = 'General'

class Metadata(BaseModel):
    total_duration: float = Field(..., description='Total processing time in seconds.')
    usage: dict = Field(..., description='Token usage details from the API response.')

class SupportTicket(BaseModel):
    priority: Priority = Field(..., description='The priority level of the support ticket.')
    department: Department = Field(..., description='The department responsible for handling the issue.')
    summary: str = Field(..., description='A brief summary of the issue in 3 sentences or less.')

class SupportResponse(BaseModel):
    intent: str = Field(..., description='The identified intent of the support ticket.')
    response_text: str = Field(..., description='The generated response to the support ticket.')
    metadata: Metadata = Field(..., description='Metadata about the processing of the support ticket.')

class ModelInterface:
    def infer_response(self, text: str) -> SupportResponse:
        raise NotImplementedError

class SLMModel(ModelInterface):
    def infer_response(self, text: str) -> SupportResponse:
        start = time.time()

        metadata = Metadata(
            total_duration=time.time() - start,
            usage={
                "prompt_tokens": 0,
                "completion_tokens": 0,
                "total_tokens": 0,
                "model": "SLM"
            }
        )
        return SupportResponse(
            intent="simple",
            response_text="This is a simple response generated by SLM.",
            metadata=metadata
        )

class FrontierModel(ModelInterface):
    def infer_response(self, text: str) -> SupportResponse:
        start = time.time()

        metadata = Metadata(
            total_duration=time.time() - start,
            usage={
                "prompt_tokens": 0,
                "completion_tokens": 0,
                "total_tokens": 0,
                "model": "Fontier"
            }
        )
        return SupportResponse(
            intent="complex",
            response_text="This is a complex response generated by Frontier.",
            metadata=metadata
        )

def classify_intent(text: str) -> str:
    simple_keywords = ["status", "thank you", "resolved", "close tiket"]
    complex_keywords = ["billing", "charge", "refund", "error", "troubleshoot", "not working"]
    text_lower = text.lower()

    if any(word in text_lower for word in simple_keywords):
        return "simple"
    if any(word in text_lower for word in complex_keywords):
        return "complex"
    return "simple"

class SupportAIService:
    def __init__(self):
        self.slm = SLMModel()
        self.frontier = FrontierModel()

    def handle_ticket(self, text: str) -> SupportResponse:
        intent = classify_intent(text)
        if intent == "simple":
            return self.slm.infer_response(text)
        else:
            return self.frontier.infer_response(text)

if __name__ == "__main__":
    service = SupportAIService()
    test_cases = [
        "Can you check the status of my ticket?",
        "Thank you for your help, please close the ticket.",
        "I was charged twice for my subscription and need a refund.",
        "There is an error when I try to log in.",
        "Just wanted to say thanks!"
    ]

    for i, text in enumerate(test_cases, 1):
        print(f"\nTest case {i}: {text}")
        response = service.handle_ticket(text)
        print(f"Intent: {response.intent}")
        print(f"Response: {response.response_text}")
        print(f"Metadata: {response.metadata.model_dump()}")