name: Deploy Enterprise Proxy to AWS

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ "main" ]
#     paths:
#         - 'pii-scrubber-capstone/**'
#         - '.github/workflows/deploy.yml'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: pii-scrubber-proxy
  WORKING_DIR: ./pii-scrubber-capstone

jobs:
  build-and-deploy:
    name: Build & Push to Amazon ECR
    runs-on: ubuntu-latest
    
    # 🚨 CRITICAL FIX: Grant GitHub permission to generate the OIDC token
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 1: Securely log in to AWS (No hardcoded keys!)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::821184870795:role/GithubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    # Step 2: Log in to the Container Registry
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 3: Build the FastAPI Docker container and push it
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "✅ Container successfully pushed to AWS!"
